import * as THREE from 'three';import{World}from'./world.js';import{Player}from'./player.js';import{NPCManager}from'./npc.js';import{Capture}from'./capture.js';import{Battle}from'./battle.js';import{UI}from'./ui.js';
document.documentElement.style.touchAction='none';document.body.style.touchAction='none';
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,300),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;document.querySelector('#game').appendChild(renderer.domElement);
const ui=new UI(),world=new World(scene),player=new Player(scene),npcs=new NPCManager(scene),cap=new Capture(),battle=new Battle(ui,cap,player);const keys={};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='KeyC')freeCapture();if(e.code==='KeyB')ui.pc(player.party);if(e.code==='KeyH'){player.heal();ui.toast('Equipe curada!')}if(e.code==='Escape')ui.closeAll()});addEventListener('keyup',e=>keys[e.code]=false);
let drag=false,lx=0,ly=0;renderer.domElement.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag||ui.modalOpen())return;player.yaw-=(e.clientX-lx)*.006;player.pitch=THREE.MathUtils.clamp(player.pitch-(e.clientY-ly)*.004,-.7,.55);lx=e.clientX;ly=e.clientY});
function wild(){let b=null,d=5;for(const w of world.wilds)if(w.userData.active){const x=w.position.distanceTo(player.group.position);if(x<d){d=x;b=w}}return b}
function interact(){if(ui.modalOpen())return;const n=npcs.nearest(player.group.position,4);if(n)return ui.dialog(n.userData.data);const w=wild();if(w){w.userData.pokemon._backBonus=w.userData.back?.8:0;ui.aim(w.userData.pokemon,()=>throwBall(w),()=>{ui.closeAll();battle.start(w.userData.pokemon)})}}
function freeCapture(){const w=wild();if(w)interact();else ui.toast('Aproxime-se de uma criatura no mato.')}
function throwBall(w){const m=w.userData.pokemon;m._backBonus=w.userData.back?.08:0;const r=cap.attempt(m);if(r.success){player.add({...m,hp:m.maxHp});world.removeWild(w);ui.toast(`✨ ${m.name} capturado fora de batalha!`)}else{w.userData.alert=2;ui.toast(`${m.name} escapou!`)}ui.closeAll()}
document.querySelector('#mInteract').onclick=interact;document.querySelector('#mAim').onclick=freeCapture;document.querySelector('#mPC').onclick=()=>ui.pc(player.party);
let joy={x:0,y:0};const j=document.querySelector('#joy');if(j){j.addEventListener('pointerdown',e=>{j.setPointerCapture?.(e.pointerId)});j.addEventListener('pointermove',e=>{const r=j.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;joy.x=THREE.MathUtils.clamp((e.clientX-cx)/(r.width/2),-1,1);joy.y=THREE.MathUtils.clamp((e.clientY-cy)/(r.height/2),-1,1);keys.KeyA=joy.x<-.25;keys.KeyD=joy.x>.25;keys.KeyW=joy.y<-.25;keys.KeyS=joy.y>.25});j.addEventListener('pointerup',()=>{joy.x=joy.y=0;keys.KeyA=keys.KeyD=keys.KeyW=keys.KeyS=false});j.addEventListener('pointercancel',()=>{joy.x=joy.y=0;keys.KeyA=keys.KeyD=keys.KeyW=keys.KeyS=false})}
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(!ui.modalOpen())player.update(dt,keys);npcs.update(dt);world.update(dt,player.group.position);const target=player.group.position.clone().add(new THREE.Vector3(0,1.3,0)),off=new THREE.Vector3(Math.sin(player.yaw)*Math.cos(player.pitch)*6,2.8+Math.sin(player.pitch)*3,Math.cos(player.yaw)*Math.cos(player.pitch)*6);camera.position.lerp(target.clone().add(off),.12);camera.lookAt(target);document.querySelector('#status').innerHTML=`Criaturas: ${player.party.length}<br>Pokébolas: ∞<br>Próximo: ${wild()?.userData.pokemon.name||'—'}`;renderer.render(scene,camera)}addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});loop();
