import * as THREE from 'three';import {randomWildPokemon,makePokemonModel} from './pokemon.js';
export class World{constructor(scene){this.scene=scene;this.wilds=[];this.houses=[];this.t=0;this.build();this.spawn();this.housesBuild()}
build(){this.scene.background=new THREE.Color(0x9bc7e8);this.scene.add(new THREE.HemisphereLight(0xbfe4ff,0x49613f,1.8));const sun=new THREE.DirectionalLight(0xffffff,2.2);sun.position.set(40,70,20);sun.castShadow=true;this.scene.add(sun);const g=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x65a85a}));g.rotation.x=-Math.PI/2;g.receiveShadow=true;this.scene.add(g);const w=new THREE.Mesh(new THREE.CircleGeometry(13,48),new THREE.MeshStandardMaterial({color:0x4aa6cf,transparent:true,opacity:.82}));w.rotation.x=-Math.PI/2;w.position.set(25,.04,-18);this.scene.add(w);for(let i=0;i<45;i++)this.tree((Math.random()-.5)*150,(Math.random()-.5)*150);for(let i=0;i<10;i++)this.grass((Math.random()-.5)*130,(Math.random()-.5)*130)}
tree(x,z){const g=new THREE.Group(),t=new THREE.Mesh(new THREE.CylinderGeometry(.45,.65,3,8),new THREE.MeshStandardMaterial({color:0x6b4329})),c=new THREE.Mesh(new THREE.SphereGeometry(2.1,10,8),new THREE.MeshStandardMaterial({color:0x287347}));t.position.y=1.5;c.position.y=4;g.add(t,c);g.position.set(x,0,z);g.userData.collider={r:1.1};this.scene.add(g)}
grass(x,z){const g=new THREE.Group();for(let i=0;i<65;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.06,.7,.06),new THREE.MeshStandardMaterial({color:0x3e8d4a}));b.position.set((Math.random()-.5)*7,.35,(Math.random()-.5)*7);g.add(b)}g.position.set(x,0,z);g.userData.grass=true;this.scene.add(g)}
spawn(){for(let i=0;i<16;i++){const p=randomWildPokemon(),m=makePokemonModel(p),a=Math.random()*Math.PI*2,r=14+Math.random()*62;m.position.set(Math.cos(a)*r,0,Math.sin(a)*r);m.userData={active:true,pokemon:p,phase:Math.random()*10,alert:0,back:false};this.scene.add(m);this.wilds.push(m)}}
housesBuild(){[[-22,-10],[34,13]].forEach((q,i)=>{const g=new THREE.Group(),b=new THREE.Mesh(new THREE.BoxGeometry(8,4.5,7),new THREE.MeshStandardMaterial({color:i?0xc98963:0xd6d3a5})),r=new THREE.Mesh(new THREE.ConeGeometry(5.8,2.8,4),new THREE.MeshStandardMaterial({color:0x8a4c3a}));b.position.y=2.25;r.position.y=5.9;r.rotation.y=Math.PI/4;g.add(b,r);g.position.set(...q.map(Number).slice(0,1),0,q[1]);g.userData.house=true;this.scene.add(g);this.houses.push(g)})}
nearestHouse(p,r){return this.houses.find(h=>h.position.distanceTo(p)<r)}removeWild(w){w.userData.active=false;w.visible=false}
update(dt,pos){this.t+=dt;for(const w of this.wilds)if(w.userData.active){const d=w.position.distanceTo(pos);w.userData.back=Math.random()>.015&&d>4;w.rotation.y+=Math.sin(this.t+w.userData.phase)*dt*.3;w.position.y=Math.abs(Math.sin(this.t*2+w.userData.phase))*.04;if(w.userData.alert>0)w.userData.alert-=dt;if(d<3){w.userData.alert=1.4;const v=w.position.clone().sub(pos).normalize();w.position.addScaledVector(v,dt*1.4)}}}}
